mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
server:
  port: 8080
wyu:
  jwt:
    secret: f4e2e52034348f86b67cde581c0f9eb5
    expire: 604800
    header: Authorization
  file:
    staticAccessPath: /local/**
    uploadAvatar: D://img/
  paiUrl: http://localhost:8080/local/
